name: Daily Progress Check

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  check-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython boto3

      - name: Check commits and send email using AWS SES
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # Change to your AWS SES region
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }} # Must be verified with AWS SES
        run: |
          import git
          import boto3
          from datetime import datetime, timedelta

          # Initialize git repo
          repo = git.Repo('.')
          
          # Check for commits in the last day
          commits = list(repo.iter_commits(since='1.day'))
          
          # Email content
          subject = ''
          body = ''
          
          if not commits:
              subject = 'No Progress Today'
              body = 'You should fuck yourself for not making any progress today!'
          else:
              subject = f'Progress Summary: {len(commits)} Commits Today'
              body = 'Commit Summary:\\n' + '\\n'.join(commit.message for commit in commits)
          
          # Send email
          ses_client = boto3.client('ses', region_name=AWS_REGION,
                                    aws_access_key_id=AWS_ACCESS_KEY_ID,
                                    aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
          response = ses_client.send_email(
              Source=SENDER_EMAIL,
              Destination={
                  'ToAddresses': [
                      RECEIVER_EMAIL,
                  ],
              },
              Message={
                  'Subject': {
                      'Data': subject
                  },
                  'Body': {
                      'Text': {
                          'Data': body
                      },
                  },
              }
          )

        shell: python
